---
title: "Projets"
format:
  html:
    toc: true
    toc-depth: 2
    toc-title: "Accès rapide"
    toc-location: left
---

Vous trouverez ci-dessous nos projets de recherche et certains outils que nous développons (ex. tableaux de bord).

## Projets de recherche {#projets}

**JA PreventNCD – European Joint Action on Non-Communicable Diseases**\
*2023–2026 — European Joint Action on NCDs*\
[Lien](https://preventncd.eu/)

------------------------------------------------------------------------

**BELCOHORT – Bringing together existing health data into a Belgian population cohort to assess the interaction between health, environment and society**\
*2023–2026 — BELSPO*\
[Lien](https://www.sciensano.be/fr/projets/rassembler-les-donnees-de-sante-existantes-et-nouvelles-dans-une-cohorte-epidemiologique-belge-afin)

------------------------------------------------------------------------

**Characterizing long COVID and its physical, mental and social implications (COVIMPACT)**\
*2021 — Sciensano*\
[Lien](https://www.sciensano.be/fr/projets/covid-long-et-ses-implications-physiques-mentales-et-sociales)

------------------------------------------------------------------------

**Improving the Preparedness of Health Systems to Reduce Mental Health and Psychosocial Concerns resulting from the COVID-19 Pandemic (RESPOND)**\
*2020–2023 — Union européenne (H2020)*\
[Lien](https://respond-project.eu/)

------------------------------------------------------------------------

**Impact of the COVID-19 epidemic and confinement and the social and mental health of the general population (Covid and I)**\
*2020 — UCLouvain*

------------------------------------------------------------------------

**Mapping and Assessment of Developments for one of the sectoral professions under Directive 2005/36/EC – nurse responsible for general care**\
*2019 — Commission européenne*

------------------------------------------------------------------------

**Organization of mental health care for adults in Belgium: benefits, barriers, gaps and overlaps in the current offer of mental health care (KCE-HSR-52)**\
*2017–2018 — KCE (Belgian Health Care Knowledge Centre)*\
[Lien](https://kce.fgov.be/en/publications/all-reports/organisation-of-mental-health-care-for-adults-in-belgium)

------------------------------------------------------------------------

**Comparing policy framework, structure, effectiveness and cost-effectiveness of functional and integrated systems of mental health care (COFI)**\
*2014–2018 — Union européenne (7e programme-cadre)*\
[Lien](https://cordis.europa.eu/project/id/602645)

------------------------------------------------------------------------

**Feasibility study of Drug Consumption Rooms in Belgium (DRUGROOM)**\
*2017 — BELSPO (Belgian Federal Science Policy Office)*\
[Lien](https://www.belspo.be/belspo/fedra/DR/DR78_DRUGROOM_summary2018_en.pdf)

------------------------------------------------------------------------

**Continuity of care for precarious people in the Brussels-Capital Region (CAPP)**\
*2014–2017 — INNOVIRIS*\

## Tableaux de bord intéractifs {#dashboard}

#### 1. Santé mentale en Wallonie - tableau de bord:

<iframe src="https://pierre-smith.shinyapps.io/sante_mentale_wallonie/" width="100%" height="500" frameborder="0">

</iframe>

[🔗](https://www.linkedin.com/in/pierre-smith-48855aa9/){target="_blank"}[Accéder au dashboard](https://pierre-smith.shinyapps.io/sante_mentale_wallonie/){target="_blank"}

#### 2. Outil de diagnostic des besoins de santé à l'échelle locale: 

<iframe src="https://pierre-smith.shinyapps.io/phm-dashboard/" width="100%" height="500" frameborder="0">

</iframe>

[🔗](https://www.linkedin.com/in/pierre-smith-48855aa9/){target="_blank"}[Accéder au dashboard](https://pierre-smith.shinyapps.io/phm-dashboard/){target="_blank"}
