---
title: "Publications"
format: html
editor: visual
---

|  |
|----|
| 40\. Petri-Romão P., Stoffers-Winterling J., Doerschner C., **Smith P**., … Lieb, K. (2025). Co-RESPOND: a federated network of cohorts on mental health and adversity during the COVID-19 pandemic. Challenges, solutions and recommendations for retrospective data harmonization*. European Journal of Psychotraumatology.* [**Lien**](https://doi.org/10.1080/20008066.2025.2517920) |
|  |
| 39\. Pinucci, I., Tedeschi, F., Serra, R. **Smith P**., et al. (2025) Resilient outcomes in people with a history of mental disorder during the COVID-19 pandemic: an international 2-years longitudinal prospective study. Soc Psychiatry Psychiatr Epidemiol. [***Lien***](https://doi.org/10.1007/s00127-025-02944-x) |
|  |
| 38\. Van Goethem, N., Van der Heyden J., **Smith, P.,** Van Hoof, W., De Schutter H., Van Bossuyt, M., De Ridder, K., Van Den Bulcke, M., Cauët, E. (2025). From concept to approval: human genomic data integration with population observational data – insights from a Belgian pilot stud. *Archives of Public Health. [**Lien**](https://archpublichealth.biomedcentral.com/articles/10.1186/s13690-025-01581-9)* |
|  |
| 37\. Atarodi, V., Mittendorfer-Rutz, E., Morillo-Cuadrado, D. **Smith P**., et al (2025) Specialized mental healthcare use for common mental disorders and prescription of antidepressants before and during the COVID-19 pandemic among working-age refugees and Swedish-born individuals – a nationwide register-based study. *BMC Public Health. [**Lien**](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-025-22028-4)* |
|  |
| 36\. Van Droogenbroeck, F., Spruyt B., Gérain P., Van den Borre L., **Smith P**., De Pauw R., Dury S. (2025). Informal caregiving and mental health: results from the Belgian health interview survey 2013 and 2018. *BMC Public Health.* [**Lien**](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-024-20957-0) |
|  |
| 35\. Monistrol-Mula, A., Giné-Vázquez, I., Caggiu, G., Conflitti, C., Gemes, K., Hecker, I., Mediavilla, R., Compagnoni, M., Pinucci, I., Winterling, J., **Smith, P.** et al. (2025). SARS-CoV-2 infection and COVID-19 outcomes across mental disorders and the role of sex: A register-based study from Catalonia. *Psychiatry Research.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S0165178124006103?via%3Dihub) |
|  |
| 34\. Muysewinkel, E., Vesentini, L., Van Deynse, H., Gisle, L., **Smith, P.**, Bruggeman, H., Bilsen, J., Van Overmeire, R. (2024) Trauma Exposure, Social Support and Mental Health in the General Population in Belgium. *European Journal of Investigation in Health, Psychology and Education.* [**Lien**](https://www.mdpi.com/2254-9625/14/7/136) |
|  |
| 33\. D’Hondt, S., Gisle, L., D., De Pauw, R., Van Cauteren, D., Demarest, S., Drieskens, S., Cornelissen, L., De Ridder, K., Charafeddine, R., **Smith, P.** Anxiety and depression in people with post-COVID condition: a Belgian population-based cohort study three months after SARS-CoV-2 infection. *Social Psychiatry and Psychiatric Epidemiology*. [**Lien**](https://link.springer.com/article/10.1007/s00127-024-02655-9) |
|  |
| 32\. Holte Stea, T., Bonsaksen, T., **Smith P.**, Steigen, AM., Løvheim Kleppang, A., Leonhardt, M., Lien, L., Vettore, M. (2024). Does pressure, bullying and low social support predict depressive symptoms, self-harm and self-directed violence? *BMC Psychiatry*. [**Lien**](https://bmcpsychiatry.biomedcentral.com/articles/10.1186/s12888-024-05696-1) |
|  |
| 31\. Nguyen Thi Khanh, H., De Troeyer, K., **Smith, P**., Demoury, C., Casas, L. (2023) The impact of ambient temperature and air pollution on SARS-CoV2 infection and Post COVID-19 condition in Belgium (2021–2022). *Environmental Research.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S0013935123028700?via%3Dihub) |
|  |
| 30.Nayani, S. Castanares-Zapatero, D., De Pauw, R., Van Cauteren, D., Demarest, S., Drieskens, S., Cornelissen, L., Devleesschauwer, B., De Ridder, K., Charafeddine, R., **Smith, P**. (2023) Classification of symptoms and associated factors of post COVID-19 condition: a longitudinal study in the Belgian population. *BMJ Open.* [**Lien**](https://bmjopen.bmj.com/content/13/10/e072726) |
|  |
| 29\. **Smith, P.**, Kristiaan, P., Van Cauteren, D., Demarest, S., Drieskens, S., De Pauw, R., Cornelissen, L.,  Devleesschauwer, G., De Ridder, K., Charafeddine, R. (2023) Post COVID-19 condition and health-related quality of life: a longitudinal cohort study in the Belgian adult population. *BMC Public Health.* [**Lien**](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-023-16336-w) |
|  |
| 28.Nguyen Thi Khanh, H., Castanares-Zapatero, D., De Pauw, R., Van Cauteren, D., Demarest, S., Drieskens, S., Cornelissen, L., Devleesschauwer, B., De Ridder, K., Charafeddine, R., **Smith, P**. (2023) Association between SARS-CoV-2 variants and post COVID-19 condition: findings from a longitudinal cohort study in the Belgian adult population. *BMC Infectious Diseases*. [**Lien**](https://pesquisa.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/fr/ppzbmed-10.21203.rs.3.rs-2765170.v1) |
|  |
| 27\. Wyper, G., McDonald, S., Haagsma, J., Devleesschauwer, B., Charalampous, P., Maini, R., **Smith, P**., Pires, S. (2023) A proposal for further developing fatigue-related post COVID-19 health states for burden of disease studies. *Archives of Public Health.* [**Lien**](https://archpublichealth.biomedcentral.com/articles/10.1186/s13690-023-01212-1) |
|  |
| 26\. Devleesschauwer, B., Willem, L., Jurčević, J., **Smith, P**.,  Scohy, A., Wyper, G., Monteiro Pires, S., Van Goethem, N., Beutels, P., Franco, N., Abrams, S., Van Cauteren, D., Speybroeck, N., Hens, N., De Pauw, R. (2023) The direct disease burden of COVID-19 in Belgium in 2020 and 2021. *BMC Public Health.* [**Lien**](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-023-16572-0) |
|  |
| 25\. Duveau, C., **Smith, P**., Lorant, V. (2023) Migration and mental health over the past 20 years: how has the situation evolved? *Archives of Public Health*. [**Lien**](https://link.springer.com/article/10.1186/s13690-023-01187-z) |
|  |
| 24\. Lorant, V., **Smith, P.**, Duveau, C. Seeber, K., Bryant, RA., Mittendorfer-Rutz, E. Melchior, M., Haró, JM., Monzio Compagnoni, M., Corrao, G., Ayuso-Mateos JL., Sijbrandij M., Nicaise, P. (2023) Psychological distress and online advice-seeking in times of COVID-19: vertical and horizontal equity of an e-mental health strategy. *Current Psychology*. [**Lien**](https://link.springer.com/article/10.1007/s12144-023-04907-4) |
|  |
| 23\. Baudewyns, V., Bruyneel, A., **Smith, P**., Servotte, JC., Dancot, J. (2022) Prevalence and factors associated with academic burnout risk among nursing and midwifery students during the COVID-19 pandemic: A cross-sectional study. *Nursing Open*. [**Lien**](https://onlinelibrary.wiley.com/doi/10.1002/nop2.1575) |
|  |
| 22\. Hecker, I., El-Aarbaoui, T., Vallez, S., Andersen, A., Ayuso-Mateos, J., Bryant, R., Corrao, G., McDaid,D., Mediavilla, R., Mittendorfer-Rutz, E., Compagnoni, M., Park, A., Riepenhausen, A., Rigotti, T., Seeber, K., Sijbrandij, M., **Smith, P.,** Tüscher, O., Walter, H., Witteveen, A., Mary-Krause, M., Melchior, M. (2022) Impact of work arrangements during the COVID-19 pandemic on mental health in France. *SSM - Population Health.* [**Lien**](https://pubmed.ncbi.nlm.nih.gov/36415675/) |
|  |
| 21\. Al, Jabouri, O., Pierre L., and **Smith P.** (2022) The stigma of people with mental health problems and the role of health care professionals: An international scoping review. *Revue Francophone Internationale de Recherche Infirmière.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S2352802822000151?via%3Dihub) |
|  |
| 20\. **Smith, P.**, Kristiaan, P., Van Cauteren, D., Demarest, S., Drieskens, S., De Pauw, R., Cornelissen, L., De Ridder, K., Charafeddine, R. (2022) Post COVID-19 condition and its physical, mental and social implications: protocol of a 2-year longitudinal cohort study in the Belgian adult population. *Archives of Public Health*. [**Lien**](https://archpublichealth.biomedcentral.com/articles/10.1186/s13690-022-00906-2) |
|  |
| 19\. Bruggeman, H., **Smith, P**., Berete, F., Demarest, S., Hermans, L., Braekman, E., Charafeddine, E., Drieskens, S., De Ridder, K., Gisle, L. (2022) Anxiety and Depression in Belgium during the First 15 Months of the COVID-19 Pandemic: A Longitudinal Study *Behavioral Sciences*. [**Lien**](https://www.mdpi.com/2076-328X/12/5/141) |
|  |
| 18\. **Smith, P.**, Nicaise, P., Lorant, V. (2022) Social integration of people with non-psychotic mental illness over the last two decades: The widening gap in the adult population in Belgium. *Social Psychiatry and Psychiatric Epidemiology.* [**Lien**](https://pubmed.ncbi.nlm.nih.gov/35606460/) |
|  |
| 17.  Khan, Y., Bruyneel, A., **Smith, P.** (2022). Determinants of the risk of burnout among nurses during the first wave of the COVID‐19 pandemic in Belgium: A cross‐sectional study.  *Journal of Nursing Management*. [**Lien**](https://onlinelibrary.wiley.com/doi/10.1111/jonm.13624) |
|  |
| 16\. Riepenhausen A., Veer I., Wackerhagen C., Reppmann Z., Köber G., Ayuso-Mateos J., Bögeman S., Corrao G., Felez-Nobrega M., Haro Abad J.,  Hermans E., van Leeuwen J., Lieb K., Lorant V., Mary-Krause M., Mediavilla R., Melchior M., Mittendorfer-Rutz E., Monzio Compagnoni M., Pan K., Puhlmann L., Roelofs K., Sijbrandij M., **Smith P.,** Tüscher O., Witteveen A., Zerban M., Kalisch R., KrögerWalter H. (2022). Coping with COVID: Risk and resilience factors for mental health in a German representative panel study. *Psychological Medicine*, 1-11. [**Lien**](https://www.cambridge.org/core/journals/psychological-medicine/article/coping-with-covid-risk-and-resilience-factors-for-mental-health-in-a-german-representative-panel-study/47B4BDFEB41E566F9FBA1B364F396F51) |
|  |
| 15\. Haegdorens F., Franck E., **Smith P.,** Bruyneel A., Monsieurs K.G., Van Bogaert P. (2021). Sufficient personal protective equipment training can reduce COVID-19 related symptoms in healthcare workers: a prospective cohort study. *International Journal of Nursing Studies.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S0020748921002777?via%3Dihub) |
|  |
| 14\. Nicaise P., Garin H., **Smith P.,** d’Oreye de Lantremange S., Leleux, L., Wyngaerden, F., Lorant V. (2021). Implementation of a computer-assisted face-to-face intervention for mapping the social support networks of patients with severe mental illness in routine clinical practice: Analysis of the appropriateness and acceptability of the intervention. *International Journal of Social Psychiatry.* [**Lien**](https://journals.sagepub.com/doi/10.1177/00207640211058977) |
|  |
| 13\. Butera S., Brasseur N., Filion N., Bruyneel A., **Smith P.** (2021) Prevalence and Associated Factors of Burnout Risk Among Intensive Care and Emergency Nurses Before and During the Coronavirus Disease 2019 Pandemic: A Cross-Sectional Study in Belgium. *Journal of Emergency Nursing.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S0099176721002452?via%3Dihub#keys0001) |
|  |
| 12\. Saidi I., Schils G., **Smith P**. (2021). La sexualité des personnes hospitalisées en services psychiatriques hospitaliers et le rôle des professionnels de la santé : une scoping review internationale. *Revue Francophone Internationale de Recherche Infirmière.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S2352802821000260) |
|  |
| 11\. Grard A., Nicaise P., **Smith P.,** Lorant V. (2021) Use of generic social services and social integration of patients with a severe mental illness in Belgium: Individual and services network determinants. *International Journal of Social Psychiatry.* [**Lien**](https://journals.sagepub.com/doi/full/10.1177/00207640211017947) |
|  |
| 10\. Lorant V., **Smith P**., Van den Broeck K., & Nicaise P. (2021). Psychological distress associated with the COVID-19 pandemic and suppression measures during the first wave in Belgium. *BMC Psychiatry*. [**Lien**](https://bmcpsychiatry.biomedcentral.com/articles/10.1186/s12888-021-03109-1) |
|  |
| 9\. **Smith P.,** Nicaise P, Thunus S, Neyens I, Walker C, Lorant V. (2021). Stakeholder coalitions and priorities around the policy goals of a nation-wide mental health care reform. *Administration and Policy in Mental Health and Mental Health Services Research.* [**Lien**](https://link.springer.com/article/10.1007/s10488-020-01100-8) |
|  |
| 8\. Bruyneel A., **Smith P**. (2021) Comparison of the prevalence of burnout risk between ICU and non-ICU nurses during the COVID-19 outbreak in French-speaking Belgium, *Intensive and Critical Care Nursing*, Jan-06-2021, [**Lien**](https://www.sciencedirect.com/science/article/pii/S0964339721000756?dgcid=coauthor#bi005) |
|  |
| 7\. Bruyneel A., **Smith P.,** Tack, J., Pirson, M. (2021). Prevalence of burnout risk and factors associated with burnout risk among ICU nurses during the COVID-19 outbreak in French speaking Belgium. *Intensive & Critical Care Nursing.* [**Lien**](https://www.sciencedirect.com/science/article/pii/S0964339721000483?dgcid=author) |
|  |
| 6\. Rens, E., **Smith P.,** Nicaise P., Lorant V., Van den Broeck K. (2021). Explaining factors of mental distress among Belgian 16 to 25 year olds during the covid-19 pandemic. *Frontiers in public health*. [**Lien**](https://www.frontiersin.org/articles/10.3389/fpsyt.2021.575553/full) |
|  |
| 5\. **Smith P.,** Nicaise P., Giacco D., Bird V.J., Soltman B., Miglietta E., Welbel M., Pfennig A., Lasalvia A., Moskalewicz J., Priebe S., Lorant V. (2020). Use of psychiatric hospitals and social integration of patients with psychiatric disorders: a prospective cohort study in five European countries. *Social Psychiatry and Psychiatric Epidemiology*. [**Lien**](https://link.springer.com/article/10.1007/s00127-020-01881-1) |
|  |
| 4\. Moore A., van Loenhout J., Moitinho de Almeida M., **Smith P.** & Guha-Sapir D. (2020) Measuring mental health burden in humanitarian settings: a critical review of assessment tools. *Global Health Action*, 13:1. [**Lien**](https://www.tandfonline.com/doi/citedby/10.1080/16549716.2020.1783957?scroll=top&needAccess=true) |
|  |
| 3\. Banse E., Bigot A., De Valkeneer C., Lorant V., Luminet O., Nicaise P., **Smith P.,** Tubeuf S., Wuillaume A. (2020). Quelques enseignements sur les impacts sociaux et économiques de la stratégie de réponse à la pandémie du coronavirus en Belgique. *Louvain Medical.* 139 (05-06): 375-382. [**Lien**](https://www.louvainmedical.be/fr/article/quelques-enseignements-sur-les-impacts-sociaux-et-economiques-de-la-strategie-de-reponse-la) |
|  |
| 2\. **Smith P**., Favril L., Delhauteur D., Vander Laenen F., Nicaise P. (2019) How to overcome political and legal barriers to the implementation of a drug consumption room: an application of the policy agenda framework to the Belgian situation. *Addiction Science & Clinical Practice*. 14, 40. [**Lien**](https://ascpjournal.biomedcentral.com/articles/10.1186/s13722-019-0169-x) |
|  |
| 1\. **Smith P**., Nicaise P., Giacco D., Bird V.J., Soltman B., Miglietta E., Welbel M., Pfennig A., Lasalvia A., Moskalewicz J., Priebe S., Lorant V. (2019). Predictors of personal continuity of care of patients with severe mental illness: A comparison across five European countries. *European Psychiatry*, Vol 56, 69-74. [**Lien**](https://www.sciencedirect.com/science/article/pii/S0924933818302050?via%3Dihub) |
|  |
